/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonK210MaixDock.description': 'A control board based on the K210 RISC-V chip that only has basic functions and leads out all IO pins.'
        },
        'ru': {
            'microPythonK210MaixDock.description': 'Плата управления на базе чипа K210 RISC-V с базовыми функциями и выведенными всеми контактами ввода-вывода.'
        },
        'zh-cn': {
            'microPythonK210MaixDock.description': '基于 K210 RISC-V 芯片的控制板，仅包含基础功能并引出所有 IO 引脚。'
        },
        'zh-tw': {
            'microPythonK210MaixDock.description': '基於 K210 RISC-V 晶片的控制板，僅包含基礎功能並引出所有 IO 接腳。'
        }
    },
    'extensions': {
        'en': {
            'microPythonK210MaixDock.modeMenu.input': 'input',
            'microPythonK210MaixDock.modeMenu.output': 'output',
            'microPythonK210MaixDock.modeMenu.inputPullup': 'input-pullup',
            'microPythonK210MaixDock.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonK210MaixDock.levelMenu.high': 'high',
            'microPythonK210MaixDock.levelMenu.low': 'low',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonK210MaixDock.eolMenu.warp': 'warp',
            'microPythonK210MaixDock.eolMenu.noWarp': 'no-warp',
            'microPythonK210MaixDock.category.pins': 'Pins',
            'microPythonK210MaixDock.category.serial': 'Serial',
            'microPythonK210MaixDock.category.console': 'Console',
            'microPythonK210MaixDock.pins.k210SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonK210MaixDock.pins.k210SetPwmOutput': 'set pwm pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonK210MaixDock.pins.k210SetServoOutput': 'set servo pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.k210AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonK210MaixDock.serial.k210SerialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': 'serial [NO] read a line',
            'microPythonK210MaixDock.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonK210MaixDock.modeMenu.input': 'input',
            'microPythonK210MaixDock.modeMenu.output': 'output',
            'microPythonK210MaixDock.modeMenu.inputPullup': 'input-pullup',
            'microPythonK210MaixDock.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonK210MaixDock.levelMenu.high': 'high',
            'microPythonK210MaixDock.levelMenu.low': 'low',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonK210MaixDock.eolMenu.warp': 'warp',
            'microPythonK210MaixDock.eolMenu.noWarp': 'no-warp',
            'microPythonK210MaixDock.category.pins': 'Pins',
            'microPythonK210MaixDock.category.serial': 'Serial',
            'microPythonK210MaixDock.category.console': 'Console',
            'microPythonK210MaixDock.pins.k210SetPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonK210MaixDock.pins.k210SetPwmOutput': 'set pwm pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonK210MaixDock.pins.k210SetServoOutput': 'set servo pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.k210AttachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonK210MaixDock.serial.k210SerialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': 'serial [NO] read a line',
            'microPythonK210MaixDock.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonK210MaixDock.modeMenu.input': '输入',
            'microPythonK210MaixDock.modeMenu.output': '输出',
            'microPythonK210MaixDock.modeMenu.inputPullup': '上拉输入',
            'microPythonK210MaixDock.modeMenu.inputPulldown': '下拉输入',
            'microPythonK210MaixDock.levelMenu.high': '高',
            'microPythonK210MaixDock.levelMenu.low': '低',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': '电平变化',
            'microPythonK210MaixDock.eolMenu.warp': '换行',
            'microPythonK210MaixDock.eolMenu.noWarp': '不换行',
            'microPythonK210MaixDock.category.pins': '引脚',
            'microPythonK210MaixDock.category.serial': '串口',
            'microPythonK210MaixDock.category.console': '控制台',
            'microPythonK210MaixDock.pins.k210SetPinMode': '设置引脚 [PIN] 模式为 [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': '设置数字引脚 [PIN] 输出为 [LEVEL]',
            'microPythonK210MaixDock.pins.k210SetPwmOutput': '设置 PWM 引脚 [PIN] 使用通道 [CH] 输出为 [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': '读取数字引脚 [PIN]',
            'microPythonK210MaixDock.pins.k210SetServoOutput': '设置舵机引脚 [PIN] 使用通道 [CH] 输出为 [OUT]',
            'microPythonK210MaixDock.pins.k210AttachInterrupt': '当引脚 [PIN] 检测到 [MODE] 时执行',
            'microPythonK210MaixDock.serial.k210SerialBegin': '串口 [NO] 初始化 波特率 [BAUD] 引脚 RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': '串口 [NO] 打印 [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': '串口 [NO] 读取一行',
            'microPythonK210MaixDock.console.consolePrint': '打印 [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': '提示 [TEXT] 并读取输入'
        },
        'zh-tw': {
            'microPythonK210MaixDock.modeMenu.input': '輸入',
            'microPythonK210MaixDock.modeMenu.output': '輸出',
            'microPythonK210MaixDock.modeMenu.inputPullup': '上拉輸入',
            'microPythonK210MaixDock.modeMenu.inputPulldown': '下拉輸入',
            'microPythonK210MaixDock.levelMenu.high': '高',
            'microPythonK210MaixDock.levelMenu.low': '低',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': '電平變化',
            'microPythonK210MaixDock.eolMenu.warp': '換行',
            'microPythonK210MaixDock.eolMenu.noWarp': '不換行',
            'microPythonK210MaixDock.category.pins': '引腳',
            'microPythonK210MaixDock.category.serial': '串列',
            'microPythonK210MaixDock.category.console': '控制台',
            'microPythonK210MaixDock.pins.k210SetPinMode': '設定引腳 [PIN] 模式為 [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': '設定數位引腳 [PIN] 輸出為 [LEVEL]',
            'microPythonK210MaixDock.pins.k210SetPwmOutput': '設定 PWM 引腳 [PIN] 使用通道 [CH] 輸出為 [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': '讀取數位引腳 [PIN]',
            'microPythonK210MaixDock.pins.k210SetServoOutput': '設定伺服引腳 [PIN] 使用通道 [CH] 輸出為 [OUT]',
            'microPythonK210MaixDock.pins.k210AttachInterrupt': '當引腳 [PIN] 偵測到 [MODE] 時執行',
            'microPythonK210MaixDock.serial.k210SerialBegin': '串列 [NO] 初始化 鮑率 [BAUD] 接腳 RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': '串列 [NO] 印出 [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': '串列 [NO] 讀取一行',
            'microPythonK210MaixDock.console.consolePrint': '印出 [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': '提示 [TEXT] 並讀取輸入'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
