/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonK210MaixDock.description': 'A control board based on the K210 RISC-V chip that only has basic functions and leads out all IO pins.',
            'microPythonK210MaixDock.examples.blink.name': 'Blink',
            'microPythonK210MaixDock.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonK210MaixDock.examples.button.name': 'Button',
            'microPythonK210MaixDock.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonK210MaixDock.examples.fade.name': 'Fade',
            'microPythonK210MaixDock.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonK210MaixDock.examples.servoSweep.name': 'Servo Sweep',
            'microPythonK210MaixDock.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonK210MaixDock.examples.consolePrint.name': 'Console Print',
            'microPythonK210MaixDock.examples.consolePrint.description': 'Print messages to the terminal.',
            'microPythonK210MaixDock.firmware.lvgl': 'MaixPy with LVGL (kmodel V3)',
            'microPythonK210MaixDock.firmware.standard': 'MaixPy Standard (kmodel V4)'
        },
        'ru': {
            'microPythonK210MaixDock.description': 'A control board based on the K210 RISC-V chip that only has basic functions and leads out all IO pins.',
            'microPythonK210MaixDock.examples.blink.name': 'Blink',
            'microPythonK210MaixDock.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonK210MaixDock.examples.button.name': 'Button',
            'microPythonK210MaixDock.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonK210MaixDock.examples.fade.name': 'Fade',
            'microPythonK210MaixDock.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonK210MaixDock.examples.servoSweep.name': 'Servo Sweep',
            'microPythonK210MaixDock.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonK210MaixDock.examples.consolePrint.name': 'Console Print',
            'microPythonK210MaixDock.examples.consolePrint.description': 'Print messages to the terminal.',
            'microPythonK210MaixDock.firmware.lvgl': 'MaixPy with LVGL (kmodel V3)',
            'microPythonK210MaixDock.firmware.standard': 'MaixPy Standard (kmodel V4)'
        },
        'zh-cn': {
            'microPythonK210MaixDock.description': 'A control board based on the K210 RISC-V chip that only has basic functions and leads out all IO pins.',
            'microPythonK210MaixDock.examples.blink.name': 'Blink',
            'microPythonK210MaixDock.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonK210MaixDock.examples.button.name': 'Button',
            'microPythonK210MaixDock.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonK210MaixDock.examples.fade.name': 'Fade',
            'microPythonK210MaixDock.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonK210MaixDock.examples.servoSweep.name': 'Servo Sweep',
            'microPythonK210MaixDock.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonK210MaixDock.examples.consolePrint.name': 'Console Print',
            'microPythonK210MaixDock.examples.consolePrint.description': 'Print messages to the terminal.',
            'microPythonK210MaixDock.firmware.lvgl': 'MaixPy with LVGL (kmodel V3)',
            'microPythonK210MaixDock.firmware.standard': 'MaixPy Standard (kmodel V4)'
        },
        'zh-tw': {
            'microPythonK210MaixDock.description': 'A control board based on the K210 RISC-V chip that only has basic functions and leads out all IO pins.',
            'microPythonK210MaixDock.examples.blink.name': 'Blink',
            'microPythonK210MaixDock.examples.blink.description': 'Make the on-board LED blink.',
            'microPythonK210MaixDock.examples.button.name': 'Button',
            'microPythonK210MaixDock.examples.button.description': 'Light up the LED while a push button is pressed.',
            'microPythonK210MaixDock.examples.fade.name': 'Fade',
            'microPythonK210MaixDock.examples.fade.description': 'Smoothly fade an LED in and out using PWM.',
            'microPythonK210MaixDock.examples.servoSweep.name': 'Servo Sweep',
            'microPythonK210MaixDock.examples.servoSweep.description': 'Sweep a servo back and forth between 0 and 180 degrees.',
            'microPythonK210MaixDock.examples.consolePrint.name': 'Console Print',
            'microPythonK210MaixDock.examples.consolePrint.description': 'Print messages to the terminal.',
            'microPythonK210MaixDock.firmware.lvgl': 'MaixPy with LVGL (kmodel V3)',
            'microPythonK210MaixDock.firmware.standard': 'MaixPy Standard (kmodel V4)'
        }
    },
    'extensions': {
        'en': {
            'microPythonK210MaixDock.modeMenu.input': 'input',
            'microPythonK210MaixDock.modeMenu.output': 'output',
            'microPythonK210MaixDock.modeMenu.inputPullup': 'input-pullup',
            'microPythonK210MaixDock.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonK210MaixDock.levelMenu.high': 'high',
            'microPythonK210MaixDock.levelMenu.low': 'low',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonK210MaixDock.eolMenu.warp': 'warp',
            'microPythonK210MaixDock.eolMenu.noWarp': 'no-warp',
            'microPythonK210MaixDock.category.pins': 'Pins',
            'microPythonK210MaixDock.category.serial': 'Serial',
            'microPythonK210MaixDock.category.console': 'Console',
            'microPythonK210MaixDock.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonK210MaixDock.pins.setPwmOutput': 'set pwm pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonK210MaixDock.pins.setServoOutput': 'set servo pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonK210MaixDock.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': 'serial [NO] read a line',
            'microPythonK210MaixDock.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonK210MaixDock.modeMenu.input': 'input',
            'microPythonK210MaixDock.modeMenu.output': 'output',
            'microPythonK210MaixDock.modeMenu.inputPullup': 'input-pullup',
            'microPythonK210MaixDock.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonK210MaixDock.levelMenu.high': 'high',
            'microPythonK210MaixDock.levelMenu.low': 'low',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonK210MaixDock.eolMenu.warp': 'warp',
            'microPythonK210MaixDock.eolMenu.noWarp': 'no-warp',
            'microPythonK210MaixDock.category.pins': 'Pins',
            'microPythonK210MaixDock.category.serial': 'Serial',
            'microPythonK210MaixDock.category.console': 'Console',
            'microPythonK210MaixDock.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonK210MaixDock.pins.setPwmOutput': 'set pwm pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonK210MaixDock.pins.setServoOutput': 'set servo pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonK210MaixDock.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': 'serial [NO] read a line',
            'microPythonK210MaixDock.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonK210MaixDock.modeMenu.input': 'input',
            'microPythonK210MaixDock.modeMenu.output': 'output',
            'microPythonK210MaixDock.modeMenu.inputPullup': 'input-pullup',
            'microPythonK210MaixDock.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonK210MaixDock.levelMenu.high': 'high',
            'microPythonK210MaixDock.levelMenu.low': 'low',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonK210MaixDock.eolMenu.warp': 'warp',
            'microPythonK210MaixDock.eolMenu.noWarp': 'no-warp',
            'microPythonK210MaixDock.category.pins': 'Pins',
            'microPythonK210MaixDock.category.serial': 'Serial',
            'microPythonK210MaixDock.category.console': 'Console',
            'microPythonK210MaixDock.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonK210MaixDock.pins.setPwmOutput': 'set pwm pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonK210MaixDock.pins.setServoOutput': 'set servo pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonK210MaixDock.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': 'serial [NO] read a line',
            'microPythonK210MaixDock.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-tw': {
            'microPythonK210MaixDock.modeMenu.input': 'input',
            'microPythonK210MaixDock.modeMenu.output': 'output',
            'microPythonK210MaixDock.modeMenu.inputPullup': 'input-pullup',
            'microPythonK210MaixDock.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonK210MaixDock.levelMenu.high': 'high',
            'microPythonK210MaixDock.levelMenu.low': 'low',
            'microPythonK210MaixDock.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonK210MaixDock.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonK210MaixDock.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonK210MaixDock.eolMenu.warp': 'warp',
            'microPythonK210MaixDock.eolMenu.noWarp': 'no-warp',
            'microPythonK210MaixDock.category.pins': 'Pins',
            'microPythonK210MaixDock.category.serial': 'Serial',
            'microPythonK210MaixDock.category.console': 'Console',
            'microPythonK210MaixDock.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonK210MaixDock.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonK210MaixDock.pins.setPwmOutput': 'set pwm pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonK210MaixDock.pins.setServoOutput': 'set servo pin [PIN] use channel [CH] out [OUT]',
            'microPythonK210MaixDock.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonK210MaixDock.serial.serialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonK210MaixDock.serial.serialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonK210MaixDock.serial.serialReadALine': 'serial [NO] read a line',
            'microPythonK210MaixDock.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonK210MaixDock.console.consoleInput': 'prompt [TEXT] and read input'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
